---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aws-example-octodex
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aws-example-octodex
    spec:
      containers:
      - name: aws-example-octodex
        image: 064004006639.dkr.ecr.us-east-1.amazonaws.com/skynet-eks:dd577ff92fa374ea2064218df2cd22d5ea0d8e50
        # image1: REGISTRY/IMAGE:TAG
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
